name: FKW_tools
channels:
  - defaults
  - conda-forge
  - pytorch  
dependencies:
  - python=3.11 
  - matplotlib=3.10.0
  - numpy=2.1.1
  - pandas=2.2.3
  - scipy=1.15.1
  - ultralytics=8.3
  - pytorch::pytorch 
  - pytorch::torchvision 
  - cpuonly # CPU only because there is only a CPU on the RPi 